language: php
cache:
  - $HOME/.composer/cache/files
dist: bionic
php:
  - '8.0'
services:
  - mysql
before_install:
 - composer self-update
 - mysql -e 'CREATE DATABASE portal_test_db;'
before_script:
 - composer install --no-interaction --quiet
script:
 - phpunit
 - bash <(curl -s https://codecov.io/bash)
